// Regenerates src/renderer/src/render/marquee-budmo-data.ts from the Budmo Jiggler
// font, so the app needs no font file / opentype at runtime.
//
// Font: "Budmo Jiggler" by Ray Larabie / Typodermic (freeware). Not committed
// (license). Get it (e.g. `curl -L -o /tmp/budmo.zip "https://dl.dafont.com/dl/?f=budmo"`
// then unzip) and point FONT below at the .otf/.ttf.
//
// Per glyph we split the outline into contours and classify each: a small, roughly
// square contour (w < em*0.2, |w-h| < w*0.45) is a light BULB; everything else is
// the letter SILHOUETTE (frame + counters, filled even-odd). 1 bulb = 1 DMX channel.
//
// Run: node tools/bake-budmo.mjs   (needs opentype.js in node_modules)
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
const require = createRequire(import.meta.url)
const opentype = require('opentype.js')

const FONT = process.env.BUDMO_FONT || '/tmp/budmo/budmo jiggler.otf'
const OUT = new URL('../src/renderer/src/render/marquee-budmo-data.ts', import.meta.url)
const SIZE = 1000
const buf = readFileSync(FONT)
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength))
const em = (n) => +(n / SIZE).toFixed(4)

function contoursOf(path) {
  const cs = []
  let cur = null
  for (const c of path.commands) {
    if (c.type === 'M') { cur = [c]; cs.push(cur) } else if (cur) cur.push(c)
  }
  return cs
}
function bbox(cmds) {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity
  const add = (x, y) => { if (x < x0) x0 = x; if (y < y0) y0 = y; if (x > x1) x1 = x; if (y > y1) y1 = y }
  for (const c of cmds) {
    if (c.x != null) add(c.x, c.y)
    if (c.x1 != null) add(c.x1, c.y1)
    if (c.x2 != null) add(c.x2, c.y2)
  }
  return { w: x1 - x0, h: y1 - y0, cx: (x0 + x1) / 2, cy: (y0 + y1) / 2 }
}
function silPath(cs) {
  let d = ''
  for (const cmds of cs) for (const c of cmds) {
    if (c.type === 'M') d += `M${em(c.x)} ${em(c.y)}`
    else if (c.type === 'L') d += `L${em(c.x)} ${em(c.y)}`
    else if (c.type === 'C') d += `C${em(c.x1)} ${em(c.y1)} ${em(c.x2)} ${em(c.y2)} ${em(c.x)} ${em(c.y)}`
    else if (c.type === 'Q') d += `Q${em(c.x1)} ${em(c.y1)} ${em(c.x)} ${em(c.y)}`
    else if (c.type === 'Z') d += 'Z'
  }
  return d
}

const CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
const data = {}
for (const ch of CHARS) {
  const g = font.charToGlyph(ch)
  const cs = contoursOf(g.getPath(0, 0, SIZE))
  const bulbs = []
  const sil = []
  for (const cmds of cs) {
    const b = bbox(cmds)
    if (b.w < SIZE * 0.2 && Math.abs(b.w - b.h) < b.w * 0.45) bulbs.push([em(b.cx), em(b.cy), em(Math.max(b.w, b.h) * 0.5)])
    else sil.push(cmds)
  }
  data[ch] = { adv: em((g.advanceWidth / font.unitsPerEm) * SIZE), sil: silPath(sil), bulbs }
}
data[' '] = { adv: em((font.charToGlyph(' ').advanceWidth / font.unitsPerEm) * SIZE), sil: '', bulbs: [] }

const header = `/* AUTO-GENERATED by tools/bake-budmo.mjs — Budmo Jiggler (Ray Larabie / Typodermic,
 * freeware) baked so the app needs no font file / opentype at runtime. Coords are em
 * units: baseline y=0, glyph extends to -y (upward). Each glyph: adv (advance width),
 * sil (silhouette SVG path, fill even-odd), bulbs ([x,y,r] centre + radius). 1 bulb = 1 DMX ch. */
export interface BudmoGlyph {
  adv: number
  sil: string
  bulbs: [number, number, number][]
}
export const BUDMO_UNITS_PER_EM = 1
export const BUDMO: Record<string, BudmoGlyph> = `
const body = JSON.stringify(data, null, 0).replace(/"(\w| )":/g, (m, k) => `'${k}':`)
writeFileSync(OUT, `${header}${body}\n`)
const totalBulbs = Object.values(data).reduce((s, g) => s + g.bulbs.length, 0)
console.log('wrote', OUT.pathname, 'glyphs=' + Object.keys(data).length, 'bulbs=' + totalBulbs)
